---
name: build-and-test
on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java-version: [ '8', '17' ]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Java ${{ matrix.java-version }}
        uses: actions/setup-java@v2
        with:
          java-version: ${{ matrix.java-version }}
          distribution: temurin
          java-package: jdk

      - name: Set up Maven
        uses: stCarolas/setup-maven@v4.5
        with:
          maven-version: 3.9.1

      - name: build application
        shell: bash
        run: |
          mvn clean install 
      - run: mkdir artifacts && cp target/*.jar artifacts
      - uses: actions/upload-artifact@v4
        with:
         name: Package
         path: artifacts
